dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
      - libglew-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcb1-dev 
      - libxcomposite-dev 
      - libxcursor-dev 
      - libxcomposite-dev 

script:
  - sudo ln -s /usr/bin/gcc-5 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  - gcc -v && g++ -v && cmake --version
  - mkdir build && cd build
  - cmake .. -DUSE_GLEW=ON
  - cmake --build .